### ISSUE TITLE
lemmy-help panics on classes with no fields

### ISSUE THREAD

**Issue by Julian** [numToStr/lemmy-help#5]
A file containing (minimized):

```
local rpc = {}

---@class RpcRef

return rpc
```

seems to produce:

```
⊙  ~/Desktop/lemmy-help lua/lean/rpc.lua                                                                                                                                          julian@Airm ●
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.3.0/src/lib.rs:364:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      ~/Desktop/lemmy-help lua/lean/rpc.lua
```

where `RUST_BACKTRACE` says:

```
⊙  RUST_BACKTRACE=full ~/Desktop/lemmy-help lua/lean/rpc.lua                                                                                                                      julian@Airm ●
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/papergrid-0.3.0/src/lib.rs:364:17
stack backtrace:
   0:        0x104ea836e - __mh_execute_header
   1:        0x104e3b4bb - __mh_execute_header
   2:        0x104ea77be - __mh_execute_header
   3:        0x104eab755 - __mh_execute_header
   4:        0x104eabe15 - __mh_execute_header
   5:        0x104eab9c4 - __mh_execute_header
   6:        0x104eab939 - __mh_execute_header
   7:        0x104eab8f5 - __mh_execute_header
   8:        0x104eb18e3 - __mh_execute_header
   9:        0x104eb18a6 - __mh_execute_header
  10:        0x104e79e26 - __mh_execute_header
  11:        0x104e52c2f - __mh_execute_header
  12:        0x104e5691a - __mh_execute_header
  13:        0x104e3b4bb - __mh_execute_header
  14:        0x104e70f4e - __mh_execute_header
  15:        0x104e3b4bb - __mh_execute_header
  16:        0x104ea7624 - __mh_execute_header
  17:        0x104e0d68e - __mh_execute_header
  18:        0x104e0e059 - __mh_execute_header
  19:        0x104e0ebf4 - __mh_execute_header
zsh: abort      RUST_BACKTRACE=full ~/Desktop/lemmy-help lua/lean/rpc.lua
```

**Comment by numToStr** [comment]
Ohh yeah, I am assuming the `class` should have at least one `---@field`. I am not sure whether someone defining an empty class is a good thing or not. Anyway, I'll prevent that panic :)
